# Pipeline para Lambda
name: Deploy Lambda Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Execution
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_lanchonete_api_dns: ${{ secrets.LANCHONETE_API_DNS }}
        run: |
          terraform -chdir=infra init
          terraform -chdir=infra validate
          terraform -chdir=infra plan
          terraform -chdir=infra apply -auto-approve
